export const FETCH_QUOTE_API = 'FETCH_QUOTE_API';
export const SIGNED_IN = 'SIGNED_IN';
export const FETCH_FRONTEND = 'FETCH_FRONTEND';
export const SORT_BY_DATE = 'SORT_BY_DATE';
export const  SORT_BY_PRIORITY ='SORT_BY_PRIORITY';
export const FETCH_GITHUB_API = 'FETCH_GITHUB_API';
export const FETCH_FRONTEND_COMPLETED = 'FETCH_FRONTEND_COMPLETED';
export const PUSH_NEW_MEETING = 'PUSH_NEW_MEETING';
